import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import { Pool, getDbPoolConfig } from '../../backend/src/config/database.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// supabase/migrations là nguồn schema duy nhất và chuẩn mực của Supabase
const supabaseMigrationsDir = path.resolve(__dirname, '../../supabase/migrations');
const legacyMigrationsDir = path.resolve(__dirname, '../migrations');
export const migrationsDir = fs.existsSync(supabaseMigrationsDir) ? supabaseMigrationsDir : legacyMigrationsDir;

function calculateChecksum(content) {
  return crypto.createHash('sha256').update(content.trim()).digest('hex');
}

/**
 * Lấy danh sách toàn bộ các file migration theo thứ tự
 */
export function getMigrationFiles() {
  if (!fs.existsSync(migrationsDir)) return [];
  return fs
    .readdirSync(migrationsDir)
    .filter((file) => file.endsWith('.sql'))
    .sort();
}

/**
 * Khởi tạo bảng _schema_migrations trong schema app nếu chưa có
 */
async function ensureMigrationsTable(client) {
  const initSql = `
    CREATE SCHEMA IF NOT EXISTS app;
    CREATE TABLE IF NOT EXISTS app._schema_migrations (
      migration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(255) NOT NULL UNIQUE,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      checksum VARCHAR(64) NULL,
      execution_time_ms INT NULL
    );
  `;
  await client.query(initSql);
}

/**
 * Lấy danh sách các migration đã thực thi thành công
 */
async function getAppliedMigrations(client) {
  const result = await client.query('SELECT name, checksum, applied_at FROM app._schema_migrations ORDER BY migration_id ASC;');
  return result.rows || [];
}

/**
 * Áp dụng tất cả các migrations mới (Migrate UP)
 */
export async function migrateUp(customPool = null) {
  const pool = customPool || new Pool(getDbPoolConfig());
  const ownPool = !customPool;

  try {
    const client = await pool.connect();

    try {
      await ensureMigrationsTable(client);
      const applied = await getAppliedMigrations(client);
      const appliedMap = new Map(applied.map((m) => [m.name, m.checksum]));

      const files = getMigrationFiles();
      let appliedCount = 0;

      console.log(`🚀 Bắt đầu quá trình Migration PostgreSQL/Supabase (Tổng số file: ${files.length})...`);
      console.log(`📂 Thư mục migration nguồn: ${migrationsDir}`);

      for (const file of files) {
        const filePath = path.join(migrationsDir, file);
        const content = fs.readFileSync(filePath, 'utf8');
        const checksum = calculateChecksum(content);

        if (appliedMap.has(file)) {
          const recordedChecksum = appliedMap.get(file);
          if (recordedChecksum && recordedChecksum !== checksum) {
            console.warn(`⚠️  Cảnh báo: File ${file} đã thay đổi checksum so với lần chạy trước!`);
          }
          continue;
        }

        console.log(`  -> Đang thực thi migration: [${file}]...`);
        const startTime = Date.now();

        await client.query('BEGIN');
        try {
          await client.query(content);

          const executionTime = Date.now() - startTime;
          await client.query(
            `INSERT INTO app._schema_migrations (name, checksum, execution_time_ms)
             VALUES ($1, $2, $3)`,
            [file, checksum, executionTime]
          );

          await client.query('COMMIT');
          appliedCount++;
          console.log(`  ✅ Hoàn tất [${file}] (${executionTime}ms)`);
        } catch (error) {
          await client.query('ROLLBACK');
          console.error(`  ❌ Lỗi khi thực thi [${file}]:`, error.message);
          throw error;
        }
      }

      if (appliedCount === 0) {
        console.log('✨ Cơ sở dữ liệu Supabase đã ở trạng thái mới nhất. Không có migration nào cần chạy.');
      } else {
        console.log(`🎉 Hoàn tất thành công ${appliedCount} migration(s).`);
      }
    } finally {
      client.release();
    }
  } finally {
    if (ownPool) {
      await pool.end();
    }
  }
}

/**
 * Hiển thị trạng thái các migrations
 */
export async function migrateStatus() {
  const pool = new Pool(getDbPoolConfig());
  try {
    const client = await pool.connect();
    try {
      await ensureMigrationsTable(client);
      const applied = await getAppliedMigrations(client);
      const appliedMap = new Map(applied.map((m) => [m.name, m]));
      const files = getMigrationFiles();

      console.log('\n============================================================');
      console.log('BẢNG TRẠNG THÁI MIGRATION SUPABASE POSTGRESQL');
      console.log('============================================================');
      for (const file of files) {
        const item = appliedMap.get(file);
        if (item) {
          console.log(`[APPLIED] ${file} (vào lúc: ${item.applied_at})`);
        } else {
          console.log(`[PENDING] ${file}`);
        }
      }
      console.log('============================================================\n');
    } finally {
      client.release();
    }
  } finally {
    await pool.end();
  }
}

// Chạy trực tiếp từ CLI: node database/scripts/migrate.js [up|status]
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const cmd = process.argv[2] || 'up';
  if (cmd === 'up') {
    migrateUp().catch((err) => {
      console.error('Migration thất bại:', err);
      process.exit(1);
    });
  } else if (cmd === 'status') {
    migrateStatus().catch((err) => {
      console.error('Lỗi kiểm tra migration status:', err);
      process.exit(1);
    });
  }
}
