-- ====================================================================================
-- CƠ SỞ DỮ LIỆU: HỆ THỐNG QUẢN LÝ HỒ SƠ THÀNH TÍCH SỐ & HỖ TRỢ XÉT DUYỆT KHEN THƯỞNG LHU
-- Tác giả: Tạ Trần Vinh Quang (Phụ trách Backend / Database / Core API)
-- Giai đoạn: W1-Q1 - Chốt nghiệp vụ, Schema và API lõi (Cập nhật kiến trúc Supabase)
-- Hệ quản trị: PostgreSQL 15+ trên nền tảng Supabase
-- Quyết định kiến trúc: Schema 'app' độc lập, cô lập PostgREST Data API (anon/authenticated)
-- ====================================================================================

-- 1. THIẾT LẬP SCHEMA & PHÂN QUYỀN BẢO MẬT (ISOLATION)
CREATE SCHEMA IF NOT EXISTS app;

-- Ngăn chặn người dùng ẩn danh hoặc đăng nhập client qua Data API đọc trực tiếp dữ liệu nghiệp vụ
REVOKE ALL ON SCHEMA app FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA app REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA app REVOKE ALL ON ROUTINES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA app REVOKE ALL ON SEQUENCES FROM anon, authenticated;

-- Cấp quyền toàn phần cho backend service role và migration role
GRANT ALL ON SCHEMA app TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL ON TABLES TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL ON ROUTINES TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL ON SEQUENCES TO postgres, service_role;

-- ====================================================================================
-- 2. PHÂN HỆ ĐỊNH DANH VÀ XÁC THỰC (IDENTITY & RBAC)
-- ====================================================================================

CREATE TABLE IF NOT EXISTS app.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    password_changed_at TIMESTAMPTZ NULL,
    last_login_at TIMESTAMPTZ NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'LOCKED', 'INACTIVE', 'DELETED'))
);

CREATE INDEX IF NOT EXISTS idx_users_username ON app.users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON app.users (email);

CREATE TABLE IF NOT EXISTS app.roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app.user_roles (
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES app.roles(role_id) ON DELETE CASCADE,
    valid_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valid_to TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_user_roles_validity CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON app.user_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_active ON app.user_roles (user_id, role_id, valid_from, valid_to);

-- ====================================================================================
-- 3. PHÂN HỆ CƠ CẤU TỔ CHỨC & PHẠM VI THẨM QUYỀN (ORGANIZATION & SCOPES)
-- ====================================================================================

CREATE TABLE IF NOT EXISTS app.organization_units (
    unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    parent_id BIGINT NULL REFERENCES app.organization_units(unit_id),
    type VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_units_type CHECK (type IN ('FACULTY', 'DEPARTMENT', 'DIVISION', 'OFFICE', 'CENTER', 'UNIVERSITY'))
);

CREATE INDEX IF NOT EXISTS idx_units_parent_id ON app.organization_units (parent_id);

CREATE TABLE IF NOT EXISTS app.user_unit_scopes (
    user_unit_scope_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES app.roles(role_id) ON DELETE CASCADE,
    unit_id BIGINT NOT NULL REFERENCES app.organization_units(unit_id) ON DELETE CASCADE,
    include_descendants BOOLEAN NOT NULL DEFAULT TRUE,
    valid_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valid_to TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_user_unit_scopes_validity CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX IF NOT EXISTS idx_user_unit_scopes_lookup ON app.user_unit_scopes (user_id, role_id, unit_id);

-- ====================================================================================
-- 4. PHÂN HỆ HỒ SƠ GIẢNG VIÊN & PHÂN CÔNG (LECTURERS & ASSIGNMENTS)
-- ====================================================================================

CREATE TABLE IF NOT EXISTS app.lecturers (
    lecturer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES app.users(user_id) ON DELETE CASCADE,
    employee_code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NULL,
    title VARCHAR(50) NULL,
    degree VARCHAR(50) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lecturers_employee_code ON app.lecturers (employee_code);

CREATE TABLE IF NOT EXISTS app.lecturer_assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id BIGINT NOT NULL REFERENCES app.lecturers(lecturer_id) ON DELETE CASCADE,
    unit_id BIGINT NOT NULL REFERENCES app.organization_units(unit_id) ON DELETE CASCADE,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    valid_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valid_to TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_assignments_validity CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- Partial Unique Index: Mỗi giảng viên chỉ có đúng một đơn vị chính có hiệu lực tại một thời điểm
CREATE UNIQUE INDEX IF NOT EXISTS uq_lecturer_assignments_primary 
ON app.lecturer_assignments (lecturer_id) 
WHERE is_primary = TRUE AND (valid_to IS NULL OR valid_to >= NOW());

-- ====================================================================================
-- 5. PHÂN HỆ DANH MỤC TIÊU CHÍ (CATALOGS & CRITERIA)
-- ====================================================================================

CREATE TABLE IF NOT EXISTS app.achievement_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app.criteria (
    criterion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES app.achievement_categories(category_id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    points NUMERIC(6,2) NOT NULL DEFAULT 0.00,
    requires_evidence BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ====================================================================================
-- 6. PHÂN HỆ THÀNH TÍCH VÀ MINH CHỨNG SỐ (ACHIEVEMENTS & EVIDENCES)
-- ====================================================================================

CREATE TABLE IF NOT EXISTS app.achievements (
    achievement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criterion_id BIGINT NOT NULL REFERENCES app.criteria(criterion_id) ON DELETE RESTRICT,
    lecturer_id BIGINT NULL REFERENCES app.lecturers(lecturer_id) ON DELETE CASCADE,
    unit_id BIGINT NULL REFERENCES app.organization_units(unit_id) ON DELETE CASCADE,
    context_unit_id BIGINT NOT NULL REFERENCES app.organization_units(unit_id) ON DELETE RESTRICT,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    achievement_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    submitted_at TIMESTAMPTZ NULL,
    verified_at TIMESTAMPTZ NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Ràng buộc Chủ thể XOR (Cá nhân hoặc Tập thể)
    CONSTRAINT ck_achievements_subject_xor CHECK (
        (lecturer_id IS NOT NULL AND unit_id IS NULL) OR 
        (lecturer_id IS NULL AND unit_id IS NOT NULL)
    ),
    CONSTRAINT ck_achievements_status CHECK (
        status IN ('DRAFT', 'SUBMITTED', 'VERIFIED', 'REJECTED', 'RETURNED')
    )
);

CREATE INDEX IF NOT EXISTS idx_achievements_lecturer_id ON app.achievements (lecturer_id);
CREATE INDEX IF NOT EXISTS idx_achievements_unit_id ON app.achievements (unit_id);
CREATE INDEX IF NOT EXISTS idx_achievements_context_unit_id ON app.achievements (context_unit_id);
CREATE INDEX IF NOT EXISTS idx_achievements_status ON app.achievements (status);

CREATE TABLE IF NOT EXISTS app.evidence_files (
    evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id BIGINT NOT NULL REFERENCES app.achievements(achievement_id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    uploaded_by_user_id BIGINT NOT NULL REFERENCES app.users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_evidence_achievement_id ON app.evidence_files (achievement_id);

CREATE TABLE IF NOT EXISTS app.achievement_verifications (
    verification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id BIGINT NOT NULL REFERENCES app.achievements(achievement_id) ON DELETE CASCADE,
    verifier_user_id BIGINT NOT NULL REFERENCES app.users(user_id),
    action VARCHAR(20) NOT NULL,
    comments TEXT NULL,
    verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_verifications_action CHECK (action IN ('VERIFY', 'REJECT', 'RETURN'))
);

CREATE INDEX IF NOT EXISTS idx_verifications_achievement_id ON app.achievement_verifications (achievement_id);

-- ====================================================================================
-- 7. PHÂN HỆ ĐỢT KHEN THƯỞNG VÀ SỔ QUYẾT ĐỊNH (AWARDS)
-- ====================================================================================

CREATE TABLE IF NOT EXISTS app.award_periods (
    award_period_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_award_periods_status CHECK (status IN ('PLANNED', 'OPEN', 'IN_REVIEW', 'COMPLETED', 'CLOSED')),
    CONSTRAINT ck_award_periods_date CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS app.award_criteria (
    award_criterion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_period_id BIGINT NOT NULL REFERENCES app.award_periods(award_period_id) ON DELETE CASCADE,
    criterion_id BIGINT NOT NULL REFERENCES app.criteria(criterion_id) ON DELETE RESTRICT,
    min_points NUMERIC(6,2) NOT NULL DEFAULT 0.00,
    weight NUMERIC(4,2) NOT NULL DEFAULT 1.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app.award_applications (
    application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_period_id BIGINT NOT NULL REFERENCES app.award_periods(award_period_id) ON DELETE CASCADE,
    lecturer_id BIGINT NULL REFERENCES app.lecturers(lecturer_id) ON DELETE CASCADE,
    unit_id BIGINT NULL REFERENCES app.organization_units(unit_id) ON DELETE CASCADE,
    total_points NUMERIC(8,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_award_applications_subject_xor CHECK (
        (lecturer_id IS NOT NULL AND unit_id IS NULL) OR 
        (lecturer_id IS NULL AND unit_id IS NOT NULL)
    ),
    CONSTRAINT ck_award_applications_status CHECK (
        status IN ('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED')
    )
);

CREATE TABLE IF NOT EXISTS app.award_records (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_period_id BIGINT NOT NULL REFERENCES app.award_periods(award_period_id) ON DELETE CASCADE,
    lecturer_id BIGINT NULL REFERENCES app.lecturers(lecturer_id) ON DELETE CASCADE,
    unit_id BIGINT NULL REFERENCES app.organization_units(unit_id) ON DELETE CASCADE,
    decision_number VARCHAR(100) NOT NULL,
    decision_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RECORDED',
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_award_records_subject_xor CHECK (
        (lecturer_id IS NOT NULL AND unit_id IS NULL) OR 
        (lecturer_id IS NULL AND unit_id IS NOT NULL)
    ),
    CONSTRAINT ck_award_records_status CHECK (
        status IN ('RECORDED', 'CANCELLED')
    )
);

-- Partial Unique Index: Chống ghi nhận trùng khen thưởng
CREATE UNIQUE INDEX IF NOT EXISTS uq_award_records_lecturer_recorded 
ON app.award_records (award_period_id, lecturer_id) 
WHERE lecturer_id IS NOT NULL AND status = 'RECORDED';

CREATE UNIQUE INDEX IF NOT EXISTS uq_award_records_unit_recorded 
ON app.award_records (award_period_id, unit_id) 
WHERE unit_id IS NOT NULL AND status = 'RECORDED';

-- ====================================================================================
-- 8. PHÂN HỆ HỆ THỐNG VÀ KIỂM TOÁN (SYSTEM & AUDIT)
-- ====================================================================================

CREATE TABLE IF NOT EXISTS app.refresh_tokens (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_ip VARCHAR(50) NULL,
    user_agent VARCHAR(500) NULL,
    revoked_at TIMESTAMPTZ NULL,
    replaced_by_token_id BIGINT NULL REFERENCES app.refresh_tokens(refresh_token_id)
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON app.refresh_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON app.refresh_tokens (user_id);

CREATE TABLE IF NOT EXISTS app.audit_logs (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL REFERENCES app.users(user_id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    entity_id BIGINT NULL,
    old_values JSONB NULL,
    new_values JSONB NULL,
    ip_address VARCHAR(50) NULL,
    user_agent VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON app.audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON app.audit_logs (entity_name, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON app.audit_logs (created_at);

-- Bảng lưu vết Migration
CREATE TABLE IF NOT EXISTS app._schema_migrations (
    migration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    checksum VARCHAR(64) NULL,
    execution_time_ms INT NULL
);
