-- ==============================================================================
-- W1-P2: Tổ chức, hồ sơ, lịch sử công tác và danh mục dùng chung
-- Bổ sung trên các bảng W1-Q1 đã có; không tạo lại organization_units/lecturers.
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE app.organization_units
    ADD COLUMN IF NOT EXISTS description TEXT NULL;

CREATE TABLE app.unit_representatives (
    unit_representative_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE RESTRICT,
    unit_id BIGINT NOT NULL REFERENCES app.organization_units(unit_id) ON DELETE CASCADE,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ NULL,
    assigned_by BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_unit_representatives_validity CHECK (valid_to IS NULL OR valid_to > valid_from),
    CONSTRAINT ex_unit_representatives_no_overlap EXCLUDE USING gist (
        unit_id WITH =,
        tstzrange(valid_from, COALESCE(valid_to, 'infinity'::timestamptz), '[)') WITH &&
    )
);

CREATE INDEX idx_unit_representatives_user
    ON app.unit_representatives (user_id, valid_from, valid_to);

ALTER TABLE app.lecturer_assignments
    ADD COLUMN IF NOT EXISTS assigned_by BIGINT NULL REFERENCES app.users(user_id) ON DELETE RESTRICT;

UPDATE app.lecturer_assignments assignment
SET assigned_by = lecturer.user_id
FROM app.lecturers lecturer
WHERE assignment.lecturer_id = lecturer.lecturer_id
  AND assignment.assigned_by IS NULL;

ALTER TABLE app.lecturer_assignments
    ALTER COLUMN assigned_by SET NOT NULL;

ALTER TABLE app.lecturer_assignments
    ADD CONSTRAINT ex_lecturer_unit_assignments_no_overlap EXCLUDE USING gist (
        lecturer_id WITH =,
        unit_id WITH =,
        tstzrange(valid_from, COALESCE(valid_to, 'infinity'::timestamptz), '[)') WITH &&
    );

ALTER TABLE app.lecturer_assignments
    ADD CONSTRAINT ex_lecturer_primary_assignments_no_overlap EXCLUDE USING gist (
        lecturer_id WITH =,
        tstzrange(valid_from, COALESCE(valid_to, 'infinity'::timestamptz), '[)') WITH &&
    ) WHERE (is_primary = TRUE);

CREATE TABLE app.academic_years (
    academic_year_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_academic_years_dates CHECK (end_date > start_date)
);

CREATE UNIQUE INDEX uq_academic_years_single_current
    ON app.academic_years (is_current)
    WHERE is_current = TRUE;

CREATE TABLE app.achievement_types (
    achievement_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    applicable_subject_type VARCHAR(20) NOT NULL DEFAULT 'BOTH',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_achievement_types_subject CHECK (applicable_subject_type IN ('LECTURER', 'UNIT', 'BOTH'))
);

CREATE TABLE app.award_types (
    award_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(30) NOT NULL,
    level VARCHAR(30) NOT NULL,
    applicable_subject_type VARCHAR(20) NOT NULL DEFAULT 'BOTH',
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_award_types_category CHECK (category IN ('TITLE', 'REWARD_FORM')),
    CONSTRAINT ck_award_types_level CHECK (level IN ('FACULTY', 'UNIVERSITY', 'MINISTRY', 'STATE')),
    CONSTRAINT ck_award_types_subject CHECK (applicable_subject_type IN ('LECTURER', 'UNIT', 'BOTH'))
);

-- Cột chuyển tiếp giữ NULL để không phá dữ liệu W1-Q1 đã có; API tạo mới vẫn phải truyền achievementTypeId.
ALTER TABLE app.achievements
    ADD COLUMN IF NOT EXISTS achievement_type_id BIGINT NULL REFERENCES app.achievement_types(achievement_type_id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS academic_year_id BIGINT NULL REFERENCES app.academic_years(academic_year_id) ON DELETE RESTRICT;

CREATE INDEX idx_achievements_type_year
    ON app.achievements (achievement_type_id, academic_year_id);

ALTER TABLE app.award_records
    ADD COLUMN IF NOT EXISTS award_type_id BIGINT NULL REFERENCES app.award_types(award_type_id) ON DELETE RESTRICT;

CREATE INDEX idx_award_records_award_type
    ON app.award_records (award_type_id);
