-- ==============================================================================
-- Migration 007: Khởi tạo Đợt Khen thưởng, Hồ sơ Đề nghị & Sổ Quyết định Khen thưởng
-- (app.award_periods, app.award_criteria, app.award_applications, app.award_records)
-- ==============================================================================

-- Bảng Đợt Xét duyệt Khen thưởng
CREATE TABLE IF NOT EXISTS app.award_periods (
    award_period_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_award_periods_status CHECK (status IN ('PLANNED', 'OPEN', 'IN_REVIEW', 'COMPLETED', 'CLOSED')),
    CONSTRAINT ck_award_periods_date CHECK (end_date >= start_date)
);

-- Bảng Tiêu chí Áp dụng cho Đợt Khen thưởng
CREATE TABLE IF NOT EXISTS app.award_criteria (
    award_criterion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_period_id BIGINT NOT NULL REFERENCES app.award_periods(award_period_id) ON DELETE CASCADE,
    criterion_id BIGINT NOT NULL REFERENCES app.criteria(criterion_id) ON DELETE RESTRICT,
    min_points NUMERIC(6,2) NOT NULL DEFAULT 0.00,
    weight NUMERIC(4,2) NOT NULL DEFAULT 1.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Bảng Hồ sơ Đề nghị Khen thưởng (Applications)
CREATE TABLE IF NOT EXISTS app.award_applications (
    application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_period_id BIGINT NOT NULL REFERENCES app.award_periods(award_period_id) ON DELETE CASCADE,
    lecturer_id BIGINT NULL REFERENCES app.lecturers(lecturer_id) ON DELETE CASCADE,
    unit_id BIGINT NULL REFERENCES app.organization_units(unit_id) ON DELETE CASCADE,
    total_points NUMERIC(8,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Ràng buộc Chủ thể XOR
    CONSTRAINT ck_award_applications_subject_xor CHECK (
        (lecturer_id IS NOT NULL AND unit_id IS NULL) OR 
        (lecturer_id IS NULL AND unit_id IS NOT NULL)
    ),
    CONSTRAINT ck_award_applications_status CHECK (
        status IN ('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED')
    )
);

CREATE INDEX IF NOT EXISTS idx_award_apps_period ON app.award_applications (award_period_id);
CREATE INDEX IF NOT EXISTS idx_award_apps_lecturer ON app.award_applications (lecturer_id);
CREATE INDEX IF NOT EXISTS idx_award_apps_unit ON app.award_applications (unit_id);

-- Bảng Sổ Quyết định Khen thưởng (Award Records)
CREATE TABLE IF NOT EXISTS app.award_records (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_period_id BIGINT NOT NULL REFERENCES app.award_periods(award_period_id) ON DELETE CASCADE,
    lecturer_id BIGINT NULL REFERENCES app.lecturers(lecturer_id) ON DELETE CASCADE,
    unit_id BIGINT NULL REFERENCES app.organization_units(unit_id) ON DELETE CASCADE,
    decision_number VARCHAR(100) NOT NULL,
    decision_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RECORDED',
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Ràng buộc Chủ thể XOR
    CONSTRAINT ck_award_records_subject_xor CHECK (
        (lecturer_id IS NOT NULL AND unit_id IS NULL) OR 
        (lecturer_id IS NULL AND unit_id IS NOT NULL)
    ),
    CONSTRAINT ck_award_records_status CHECK (
        status IN ('RECORDED', 'CANCELLED')
    )
);

-- Partial Unique Index: Chống ghi nhận trùng khen thưởng trong cùng một đợt
CREATE UNIQUE INDEX IF NOT EXISTS uq_award_records_lecturer_recorded 
ON app.award_records (award_period_id, lecturer_id) 
WHERE lecturer_id IS NOT NULL AND status = 'RECORDED';

CREATE UNIQUE INDEX IF NOT EXISTS uq_award_records_unit_recorded 
ON app.award_records (award_period_id, unit_id) 
WHERE unit_id IS NOT NULL AND status = 'RECORDED';
