-- ==============================================================================
-- Migration 006: Khởi tạo Minh chứng số & Lịch sử Thẩm định Thành tích
-- (app.evidence_files, app.achievement_verifications)
-- ==============================================================================

-- Bảng Tệp Minh chứng số (Private Storage Files)
CREATE TABLE IF NOT EXISTS app.evidence_files (
    evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id BIGINT NOT NULL REFERENCES app.achievements(achievement_id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    uploaded_by_user_id BIGINT NOT NULL REFERENCES app.users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_evidence_achievement_id ON app.evidence_files (achievement_id);

-- Bảng Lịch sử Thẩm định Thành tích (Audit & Verification Log)
CREATE TABLE IF NOT EXISTS app.achievement_verifications (
    verification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id BIGINT NOT NULL REFERENCES app.achievements(achievement_id) ON DELETE CASCADE,
    verifier_user_id BIGINT NOT NULL REFERENCES app.users(user_id),
    action VARCHAR(20) NOT NULL,
    comments TEXT NULL,
    verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_verifications_action CHECK (action IN ('VERIFY', 'REJECT', 'RETURN'))
);

CREATE INDEX IF NOT EXISTS idx_verifications_achievement_id ON app.achievement_verifications (achievement_id);
