-- W2-P3: private in-app notifications. No arbitrary title/reason/file payload.
CREATE TABLE app.notifications (
 notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE RESTRICT,
 entity_type VARCHAR(20) NOT NULL CHECK (entity_type IN ('AWARD','ACHIEVEMENT')),
 entity_id BIGINT NOT NULL CHECK (entity_id > 0),
 entity_version BIGINT NOT NULL CHECK (entity_version > 1),
 from_status VARCHAR(30) NOT NULL,
 to_status VARCHAR(30) NOT NULL,
 audience VARCHAR(10) NOT NULL CHECK (audience IN ('SUBJECT','MANAGER')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 read_at TIMESTAMPTZ,
 UNIQUE(user_id, entity_type, entity_id, entity_version)
);
CREATE INDEX idx_notifications_inbox ON app.notifications(user_id, created_at DESC, notification_id DESC);
CREATE INDEX idx_notifications_unread ON app.notifications(user_id) WHERE read_at IS NULL;
ALTER TABLE app.notifications ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON app.notifications FROM anon, authenticated;
