-- ==============================================================================
-- Migration 003: Khởi tạo Cơ cấu Tổ chức & Phạm vi Thẩm quyền Đơn vị
-- (app.organization_units, app.user_unit_scopes)
-- ==============================================================================

-- Bảng Đơn vị Tổ chức (Khoa, Bộ môn, Phòng ban, Viện, Trường)
CREATE TABLE IF NOT EXISTS app.organization_units (
    unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    parent_id BIGINT NULL REFERENCES app.organization_units(unit_id),
    type VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_units_type CHECK (type IN ('FACULTY', 'DEPARTMENT', 'DIVISION', 'OFFICE', 'CENTER', 'UNIVERSITY'))
);

CREATE INDEX IF NOT EXISTS idx_units_parent_id ON app.organization_units (parent_id);

-- Bảng Phạm vi Quản lý Đơn vị của Người dùng (Scopes)
CREATE TABLE IF NOT EXISTS app.user_unit_scopes (
    user_unit_scope_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES app.roles(role_id) ON DELETE CASCADE,
    unit_id BIGINT NOT NULL REFERENCES app.organization_units(unit_id) ON DELETE CASCADE,
    include_descendants BOOLEAN NOT NULL DEFAULT TRUE,
    valid_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valid_to TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_user_unit_scopes_validity CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX IF NOT EXISTS idx_user_unit_scopes_lookup ON app.user_unit_scopes (user_id, role_id, unit_id);
