-- ==============================================================================
-- Migration 004: Khởi tạo Giảng viên, Phân công công tác & Danh mục Tiêu chí
-- (app.lecturers, app.lecturer_assignments, app.achievement_categories, app.criteria)
-- ==============================================================================

-- Bảng Hồ sơ Giảng viên
CREATE TABLE IF NOT EXISTS app.lecturers (
    lecturer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES app.users(user_id) ON DELETE CASCADE,
    employee_code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NULL,
    title VARCHAR(50) NULL,
    degree VARCHAR(50) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lecturers_employee_code ON app.lecturers (employee_code);

-- Bảng Phân công Công tác Đơn vị của Giảng viên (Assignments)
CREATE TABLE IF NOT EXISTS app.lecturer_assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id BIGINT NOT NULL REFERENCES app.lecturers(lecturer_id) ON DELETE CASCADE,
    unit_id BIGINT NOT NULL REFERENCES app.organization_units(unit_id) ON DELETE CASCADE,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    valid_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valid_to TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_assignments_validity CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- Partial Unique Index: Mỗi giảng viên chỉ có duy nhất 1 đơn vị chính đang có hiệu lực (valid_to IS NULL)
CREATE UNIQUE INDEX IF NOT EXISTS uq_lecturer_assignments_primary 
ON app.lecturer_assignments (lecturer_id) 
WHERE is_primary = TRUE AND valid_to IS NULL;

-- Bảng Danh mục Nhóm Thành tích (Categories)
CREATE TABLE IF NOT EXISTS app.achievement_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Bảng Tiêu chí Thành tích (Criteria)
CREATE TABLE IF NOT EXISTS app.criteria (
    criterion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES app.achievement_categories(category_id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    points NUMERIC(6,2) NOT NULL DEFAULT 0.00,
    requires_evidence BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
