-- ==============================================================================
-- Migration 008: Khởi tạo Bảng Hệ thống, Refresh Tokens & Nhật ký Kiểm toán (Audit Logs)
-- (app.refresh_tokens, app.audit_logs)
-- ==============================================================================

-- Bảng Quản lý Phiên làm việc & Refresh Token (Token Rotation)
CREATE TABLE IF NOT EXISTS app.refresh_tokens (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_ip VARCHAR(50) NULL,
    user_agent VARCHAR(500) NULL,
    revoked_at TIMESTAMPTZ NULL,
    replaced_by_token_id BIGINT NULL REFERENCES app.refresh_tokens(refresh_token_id)
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON app.refresh_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON app.refresh_tokens (user_id);

-- Bảng Nhật ký Kiểm toán Hệ thống (Audit Logs)
CREATE TABLE IF NOT EXISTS app.audit_logs (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL REFERENCES app.users(user_id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    entity_id BIGINT NULL,
    old_values JSONB NULL,
    new_values JSONB NULL,
    ip_address VARCHAR(50) NULL,
    user_agent VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON app.audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON app.audit_logs (entity_name, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON app.audit_logs (created_at);
