-- W3-P2: internal KPI, never verification or awards. Express-only schema app.
CREATE TABLE app.kpi_goals (
  goal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lecturer_id BIGINT REFERENCES app.lecturers(lecturer_id) ON DELETE RESTRICT,
  unit_id BIGINT REFERENCES app.organization_units(unit_id) ON DELETE RESTRICT,
  context_unit_id BIGINT NOT NULL REFERENCES app.organization_units(unit_id) ON DELETE RESTRICT,
  code VARCHAR(80) NOT NULL,
  title VARCHAR(255) NOT NULL,
  measure_unit VARCHAR(80) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  target NUMERIC NOT NULL CHECK(target >= 0),
  plan TEXT NOT NULL DEFAULT '',
  source VARCHAR(10) NOT NULL CHECK(source IN ('MANUAL','CSV')),
  source_note TEXT NOT NULL,
  status VARCHAR(12) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','ACCEPTED')),
  accepted_by BIGINT REFERENCES app.users(user_id),
  accepted_at TIMESTAMPTZ,
  created_by BIGINT NOT NULL REFERENCES app.users(user_id),
  version BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ((lecturer_id IS NULL) <> (unit_id IS NULL)),
  CHECK(period_end >= period_start),
  CHECK(period_start >= DATE '1990-01-01' AND period_end <= DATE '2100-12-31'),
  CHECK((status='DRAFT' AND accepted_by IS NULL AND accepted_at IS NULL) OR
        (status='ACCEPTED' AND accepted_by IS NOT NULL AND accepted_at IS NOT NULL))
);
CREATE UNIQUE INDEX kpi_goal_person_period ON app.kpi_goals(lecturer_id,code,period_start,period_end) WHERE lecturer_id IS NOT NULL;
CREATE UNIQUE INDEX kpi_goal_unit_period ON app.kpi_goals(unit_id,code,period_start,period_end) WHERE unit_id IS NOT NULL;
CREATE TABLE app.kpi_results (
  result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  goal_id BIGINT NOT NULL UNIQUE REFERENCES app.kpi_goals(goal_id) ON DELETE RESTRICT,
  actual NUMERIC NOT NULL CHECK(actual >= 0),
  source VARCHAR(10) NOT NULL CHECK(source IN ('MANUAL','CSV')),
  source_note TEXT NOT NULL,
  evidence_note TEXT NOT NULL,
  achievement_id BIGINT UNIQUE REFERENCES app.achievements(achievement_id) ON DELETE RESTRICT,
  created_by BIGINT NOT NULL REFERENCES app.users(user_id),
  version BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE app.kpi_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.kpi_results ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON app.kpi_goals,app.kpi_results FROM PUBLIC,anon,authenticated;
