-- W2-P2: Supabase PostgreSQL; retain legacy rows without inventing decision metadata.
CREATE TABLE app.award_decisions (
 decision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 decision_number VARCHAR(100) NOT NULL CHECK (length(trim(decision_number)) > 0),
 decision_date DATE NOT NULL, issuer VARCHAR(150) NOT NULL CHECK (length(trim(issuer)) > 0),
 title VARCHAR(255) NOT NULL, created_by BIGINT NOT NULL REFERENCES app.users(user_id),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE (issuer, decision_number, decision_date)
);
CREATE TABLE app.award_decision_files (
 decision_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 decision_id BIGINT NOT NULL REFERENCES app.award_decisions(decision_id),
 version_no INT NOT NULL CHECK (version_no > 0),
 original_file_name VARCHAR(255) NOT NULL, storage_key VARCHAR(255) NOT NULL UNIQUE,
 mime_type VARCHAR(100) NOT NULL, file_extension VARCHAR(20) NOT NULL,
 file_size BIGINT NOT NULL CHECK (file_size BETWEEN 1 AND 10485760), sha256_hash CHAR(64) NOT NULL,
 uploaded_by BIGINT NOT NULL REFERENCES app.users(user_id), uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE (decision_id, version_no)
);
ALTER TABLE app.award_records
 ALTER COLUMN award_period_id DROP NOT NULL,
 ALTER COLUMN decision_number DROP NOT NULL,
 ALTER COLUMN decision_date DROP NOT NULL,
 ALTER COLUMN status SET DEFAULT 'DRAFT',
 DROP CONSTRAINT ck_award_records_status,
 ADD COLUMN context_unit_id BIGINT REFERENCES app.organization_units(unit_id),
 ADD COLUMN decision_id BIGINT REFERENCES app.award_decisions(decision_id),
 ADD COLUMN recognition_year INT CHECK (recognition_year BETWEEN 1990 AND 2100),
 ADD COLUMN recorded_by BIGINT REFERENCES app.users(user_id),
 ADD COLUMN recorded_at TIMESTAMPTZ,
 ADD COLUMN created_by BIGINT REFERENCES app.users(user_id),
 ADD COLUMN replaces_award_record_id BIGINT REFERENCES app.award_records(record_id),
 ADD CONSTRAINT ck_award_records_status CHECK (status IN ('DRAFT','RECORDED','REVOKED','CANCELLED')),
 ADD CONSTRAINT ck_award_records_new_complete CHECK (decision_id IS NULL OR
   (context_unit_id IS NOT NULL AND recognition_year IS NOT NULL AND award_type_id IS NOT NULL AND created_by IS NOT NULL));
DROP INDEX app.uq_award_records_lecturer_recorded;
DROP INDEX app.uq_award_records_unit_recorded;
CREATE UNIQUE INDEX uq_award_records_lecturer_recorded ON app.award_records (lecturer_id,award_type_id,decision_id)
 WHERE status='RECORDED' AND lecturer_id IS NOT NULL AND decision_id IS NOT NULL;
CREATE UNIQUE INDEX uq_award_records_unit_recorded ON app.award_records (unit_id,award_type_id,decision_id)
 WHERE status='RECORDED' AND unit_id IS NOT NULL AND decision_id IS NOT NULL;
CREATE INDEX idx_award_records_scope_year ON app.award_records(context_unit_id,recognition_year,status);
CREATE INDEX idx_award_records_decision ON app.award_records(decision_id);
-- Retain award history when a legacy parent is removed.
ALTER TABLE app.award_records
 DROP CONSTRAINT award_records_lecturer_id_fkey,
 DROP CONSTRAINT award_records_unit_id_fkey,
 DROP CONSTRAINT award_records_award_period_id_fkey,
 ADD CONSTRAINT award_records_lecturer_id_fkey FOREIGN KEY(lecturer_id) REFERENCES app.lecturers(lecturer_id) ON DELETE RESTRICT,
 ADD CONSTRAINT award_records_unit_id_fkey FOREIGN KEY(unit_id) REFERENCES app.organization_units(unit_id) ON DELETE RESTRICT,
 ADD CONSTRAINT award_records_award_period_id_fkey FOREIGN KEY(award_period_id) REFERENCES app.award_periods(award_period_id) ON DELETE RESTRICT;
CREATE TABLE app.award_record_achievements (
 record_id BIGINT NOT NULL REFERENCES app.award_records(record_id),
 achievement_id BIGINT NOT NULL REFERENCES app.achievements(achievement_id),
 linked_by BIGINT NOT NULL REFERENCES app.users(user_id), PRIMARY KEY(record_id,achievement_id)
);
CREATE TABLE app.award_record_histories (
 history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 record_id BIGINT NOT NULL REFERENCES app.award_records(record_id),
 from_status VARCHAR(20), to_status VARCHAR(20) NOT NULL,
 actor_id BIGINT NOT NULL REFERENCES app.users(user_id), reason VARCHAR(1000),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
REVOKE ALL ON app.award_decisions, app.award_decision_files, app.award_record_achievements, app.award_record_histories FROM anon, authenticated;
