-- Simulation connector staging; never modifies KPI results or verified achievements.
CREATE TABLE app.external_kpi_mappings (
 employee_id VARCHAR(80) PRIMARY KEY,
 lecturer_id BIGINT NOT NULL REFERENCES app.lecturers(lecturer_id),
 created_by BIGINT NOT NULL REFERENCES app.users(user_id),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE app.external_kpi_runs (
 run_id UUID PRIMARY KEY,
 retry_of UUID REFERENCES app.external_kpi_runs(run_id),
 created_by BIGINT NOT NULL REFERENCES app.users(user_id),
 status TEXT NOT NULL CHECK(status IN ('RUNNING','COMPLETED','FAILED')),
 attempts INTEGER NOT NULL DEFAULT 0,
 summary JSONB NOT NULL DEFAULT '{}',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 finished_at TIMESTAMPTZ
);
CREATE TABLE app.external_kpi_records (
 record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 external_id VARCHAR(80) NOT NULL,
 source_version BIGINT NOT NULL,
 payload JSONB NOT NULL,
 payload_hash TEXT NOT NULL,
 lecturer_id BIGINT REFERENCES app.lecturers(lecturer_id),
 status TEXT NOT NULL CHECK(status IN ('READY','QUARANTINED','DRAFTED')),
 reason TEXT,
 achievement_id BIGINT UNIQUE REFERENCES app.achievements(achievement_id),
 version BIGINT NOT NULL DEFAULT 1,
 UNIQUE(external_id,source_version)
);
CREATE TABLE app.external_kpi_run_items (
 run_id UUID NOT NULL REFERENCES app.external_kpi_runs(run_id),
 item_index INTEGER NOT NULL,
 record_id BIGINT REFERENCES app.external_kpi_records(record_id),
 outcome TEXT NOT NULL,
 PRIMARY KEY(run_id,item_index)
);
ALTER TABLE app.external_kpi_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.external_kpi_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.external_kpi_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.external_kpi_run_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON app.external_kpi_mappings,app.external_kpi_runs,app.external_kpi_records,app.external_kpi_run_items FROM PUBLIC,anon,authenticated;
