-- ==============================================================================
-- Migration 005: Khởi tạo Bảng Hồ sơ Thành tích với Ràng buộc Chủ thể XOR và Version Concurrency
-- (app.achievements)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS app.achievements (
    achievement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criterion_id BIGINT NOT NULL REFERENCES app.criteria(criterion_id) ON DELETE RESTRICT,
    lecturer_id BIGINT NULL REFERENCES app.lecturers(lecturer_id) ON DELETE CASCADE,
    unit_id BIGINT NULL REFERENCES app.organization_units(unit_id) ON DELETE CASCADE,
    context_unit_id BIGINT NOT NULL REFERENCES app.organization_units(unit_id) ON DELETE RESTRICT,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    achievement_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    submitted_at TIMESTAMPTZ NULL,
    verified_at TIMESTAMPTZ NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Ràng buộc toàn vẹn chủ thể XOR: Một thành tích hoặc của Cá nhân Giảng viên, hoặc của Đơn vị Tập thể
    CONSTRAINT ck_achievements_subject_xor CHECK (
        (lecturer_id IS NOT NULL AND unit_id IS NULL) OR 
        (lecturer_id IS NULL AND unit_id IS NOT NULL)
    ),
    CONSTRAINT ck_achievements_status CHECK (
        status IN ('DRAFT', 'SUBMITTED', 'VERIFIED', 'REJECTED', 'RETURNED')
    )
);

CREATE INDEX IF NOT EXISTS idx_achievements_lecturer_id ON app.achievements (lecturer_id);
CREATE INDEX IF NOT EXISTS idx_achievements_unit_id ON app.achievements (unit_id);
CREATE INDEX IF NOT EXISTS idx_achievements_context_unit_id ON app.achievements (context_unit_id);
CREATE INDEX IF NOT EXISTS idx_achievements_status ON app.achievements (status);
