-- ==============================================================================
-- Migration 013: Phân hệ Minh chứng & Quản lý Phiên bản Tệp tin (W2-Q2)
-- Người phụ trách: Tạ Trần Vinh Quang (W2-Q2)
-- Bảng: app.evidences, app.evidence_files
-- ==============================================================================

-- 1. Bảng Danh mục Minh chứng (app.evidences)
CREATE TABLE IF NOT EXISTS app.evidences (
    evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id BIGINT NOT NULL REFERENCES app.achievements(achievement_id) ON DELETE RESTRICT,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    is_removed BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT NOT NULL REFERENCES app.users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_evidences_achievement_id ON app.evidences(achievement_id);
CREATE INDEX IF NOT EXISTS idx_evidences_is_removed ON app.evidences(is_removed);

-- 2. Tự động cập nhật updated_at cho app.evidences
CREATE OR REPLACE FUNCTION app.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_evidences_updated_at ON app.evidences;
CREATE TRIGGER trg_evidences_updated_at
BEFORE UPDATE ON app.evidences
FOR EACH ROW
EXECUTE FUNCTION app.update_updated_at_column();

-- 3. Nâng cấp bảng Phiên bản Tệp tin Minh chứng Bất biến (app.evidence_files)
-- Drop bảng sơ khai cũ (chưa dùng) để tái cấu trúc theo Data Dictionary 2.6
DROP TABLE IF EXISTS app.evidence_files CASCADE;

CREATE TABLE app.evidence_files (
    evidence_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_id BIGINT NOT NULL REFERENCES app.evidences(evidence_id) ON DELETE RESTRICT,
    version_no INT NOT NULL DEFAULT 1,
    original_file_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(255) NOT NULL UNIQUE,
    mime_type VARCHAR(100) NOT NULL,
    file_extension VARCHAR(20) NOT NULL,
    file_size BIGINT NOT NULL CHECK (file_size > 0 AND file_size <= 10485760),
    sha256_hash CHAR(64) NOT NULL,
    uploaded_by BIGINT NOT NULL REFERENCES app.users(user_id),
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_evidence_files_version UNIQUE (evidence_id, version_no)
);

CREATE INDEX IF NOT EXISTS idx_evidence_files_evidence_id ON app.evidence_files(evidence_id);
CREATE INDEX IF NOT EXISTS idx_evidence_files_storage_key ON app.evidence_files(storage_key);

COMMENT ON TABLE app.evidences IS 'Danh mục hồ sơ tài liệu minh chứng gắn với một thành tích';
COMMENT ON TABLE app.evidence_files IS 'Phiên bản tệp tin vật lý bất biến; thay đổi file tạo record mới với version_no tăng dần';
