-- ==============================================================================
-- Migration 016: Gửi và Xác nhận Hồ sơ Thành tích có Snapshot, Lịch sử và Concurrency (W2-Q3)
-- Người phụ trách: Tạ Trần Vinh Quang (W2-Q3)
-- Bảng: app.achievement_submissions, app.submission_evidence_files, app.achievement_status_histories
-- ==============================================================================

-- 1. Bảng AchievementSubmissions (Lưu snapshot bất biến mỗi lần bấm nộp hồ sơ)
CREATE TABLE IF NOT EXISTS app.achievement_submissions (
    submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id BIGINT NOT NULL REFERENCES app.achievements(achievement_id) ON DELETE RESTRICT,
    revision_no INT NOT NULL CHECK (revision_no > 0),
    snapshot_data JSONB NOT NULL,
    submitted_by BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE RESTRICT,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_achievement_submissions_revision UNIQUE (achievement_id, revision_no)
);

CREATE INDEX IF NOT EXISTS idx_achievement_submissions_achievement_id ON app.achievement_submissions(achievement_id);
CREATE INDEX IF NOT EXISTS idx_achievement_submissions_submitted_by ON app.achievement_submissions(submitted_by);

-- 2. Bảng SubmissionEvidenceFiles (Đóng băng các phiên bản tệp tin đính kèm tại thời điểm nộp)
CREATE TABLE IF NOT EXISTS app.submission_evidence_files (
    submission_id BIGINT NOT NULL REFERENCES app.achievement_submissions(submission_id) ON DELETE RESTRICT,
    evidence_file_id BIGINT NOT NULL REFERENCES app.evidence_files(evidence_file_id) ON DELETE RESTRICT,
    attached_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (submission_id, evidence_file_id)
);

CREATE INDEX IF NOT EXISTS idx_sub_ev_files_submission_id ON app.submission_evidence_files(submission_id);
CREATE INDEX IF NOT EXISTS idx_sub_ev_files_file_id ON app.submission_evidence_files(evidence_file_id);

-- 3. Bảng AchievementStatusHistories (Lịch sử thẩm định và chuyển trạng thái Append-only)
CREATE TABLE IF NOT EXISTS app.achievement_status_histories (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id BIGINT NOT NULL REFERENCES app.achievements(achievement_id) ON DELETE RESTRICT,
    submission_id BIGINT NULL REFERENCES app.achievement_submissions(submission_id) ON DELETE SET NULL,
    from_status VARCHAR(30) NOT NULL,
    to_status VARCHAR(30) NOT NULL,
    actor_id BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE RESTRICT,
    reason TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ach_histories_achievement_id ON app.achievement_status_histories(achievement_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ach_histories_actor_id ON app.achievement_status_histories(actor_id);

-- 4. Bổ sung verified_by vào app.achievements (nếu chưa có)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'app' AND table_name = 'achievements' AND column_name = 'verified_by'
    ) THEN
        ALTER TABLE app.achievements ADD COLUMN verified_by BIGINT REFERENCES app.users(user_id) ON DELETE SET NULL;
    END IF;
END $$;

-- 5. Thu hồi quyền truy cập Data API trực tiếp từ anon và authenticated
REVOKE ALL ON app.achievement_submissions, app.submission_evidence_files, app.achievement_status_histories FROM anon, authenticated;

COMMENT ON TABLE app.achievement_submissions IS 'Các lần nộp hồ sơ thành tích và snapshot dữ liệu bất biến (W2-Q3)';
COMMENT ON TABLE app.submission_evidence_files IS 'Liên kết đóng băng các phiên bản tệp tin minh chứng theo từng lần nộp (W2-Q3)';
COMMENT ON TABLE app.achievement_status_histories IS 'Nhật ký chuyển trạng thái và thẩm định hồ sơ thành tích (W2-Q3)';
