-- W3-P3: additive Supabase/pg migration. Preserve legacy applications as-is.
ALTER TABLE app.award_applications
 DROP CONSTRAINT ck_award_applications_status,
 ALTER COLUMN status SET DEFAULT 'DRAFT',
 ADD COLUMN target_award_type_id BIGINT REFERENCES app.award_types(award_type_id),
 ADD COLUMN context_unit_id BIGINT REFERENCES app.organization_units(unit_id),
 ADD COLUMN created_by BIGINT REFERENCES app.users(user_id),
 ADD COLUMN purpose VARCHAR(2000),
 ADD COLUMN achievement_ids BIGINT[] NOT NULL DEFAULT '{}',
 ADD COLUMN award_record_ids BIGINT[] NOT NULL DEFAULT '{}',
 ADD CONSTRAINT ck_award_applications_status CHECK(status IN
   ('DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','COUNCIL_PENDING'));
-- Cycles reuse award_periods; do not introduce a second calendar.
ALTER TABLE app.award_applications
 DROP CONSTRAINT award_applications_award_period_id_fkey,
 DROP CONSTRAINT award_applications_lecturer_id_fkey,
 DROP CONSTRAINT award_applications_unit_id_fkey,
 ADD FOREIGN KEY(award_period_id) REFERENCES app.award_periods(award_period_id) ON DELETE RESTRICT,
 ADD FOREIGN KEY(lecturer_id) REFERENCES app.lecturers(lecturer_id) ON DELETE RESTRICT,
 ADD FOREIGN KEY(unit_id) REFERENCES app.organization_units(unit_id) ON DELETE RESTRICT;
CREATE TABLE app.award_application_inputs (
 application_id BIGINT PRIMARY KEY REFERENCES app.award_applications(application_id),
 input_version INT NOT NULL CHECK(input_version=1),
 snapshot JSONB NOT NULL,
 submitted_by BIGINT NOT NULL REFERENCES app.users(user_id),
 submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE app.award_application_histories (
 history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id BIGINT NOT NULL REFERENCES app.award_applications(application_id),
 from_status VARCHAR(20), to_status VARCHAR(20) NOT NULL,
 actor_id BIGINT NOT NULL REFERENCES app.users(user_id),
 reason VARCHAR(1000), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE FUNCTION app.w3_p3_immutable_input() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Award application input snapshot is immutable'; END;
$$;
CREATE TRIGGER immutable_award_application_input BEFORE UPDATE OR DELETE ON app.award_application_inputs
 FOR EACH ROW EXECUTE FUNCTION app.w3_p3_immutable_input();
CREATE INDEX idx_award_application_scope ON app.award_applications(context_unit_id,status);
REVOKE ALL ON app.award_application_inputs,app.award_application_histories FROM anon,authenticated;
