-- ==============================================================================
-- Migration 001: Khởi tạo Schema nghiệp vụ 'app' và Thiết lập phân quyền cô lập
-- Đảm bảo Supabase PostgREST Data API (anon / authenticated) không thể truy cập bảng nghiệp vụ
-- ==============================================================================

-- 1. Tạo Schema nghiệp vụ riêng biệt
CREATE SCHEMA IF NOT EXISTS app;

-- 2. Cô lập hoàn toàn khỏi anon và authenticated roles của Supabase PostgREST Data API
REVOKE ALL ON SCHEMA app FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA app REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA app REVOKE ALL ON ROUTINES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA app REVOKE ALL ON SEQUENCES FROM anon, authenticated;

-- 3. Cấp toàn quyền cho vai trò Backend (postgres / service_role / db migration)
GRANT ALL ON SCHEMA app TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL ON TABLES TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL ON ROUTINES TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL ON SEQUENCES TO postgres, service_role;

-- 4. Bảng lưu vết lịch sử migration của hệ thống
CREATE TABLE IF NOT EXISTS app._schema_migrations (
    migration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    checksum VARCHAR(64) NULL,
    execution_time_ms INT NULL
);
