-- ==============================================================================
-- Migration 002: Khởi tạo bảng Định danh & Phân quyền RBAC (app.users, app.roles, app.user_roles)
-- ==============================================================================

-- Bảng Người dùng
CREATE TABLE IF NOT EXISTS app.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    password_changed_at TIMESTAMPTZ NULL,
    last_login_at TIMESTAMPTZ NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'DELETED'))
);

CREATE INDEX IF NOT EXISTS idx_users_username ON app.users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON app.users (email);

-- Bảng Vai trò Hệ thống (Roles)
CREATE TABLE IF NOT EXISTS app.roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Bảng Gán Vai trò Người dùng (UserRoles)
CREATE TABLE IF NOT EXISTS app.user_roles (
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES app.roles(role_id) ON DELETE CASCADE,
    valid_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valid_to TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_user_roles_validity CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON app.user_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_active ON app.user_roles (user_id, role_id, valid_from, valid_to);
