-- ==============================================================================
-- Migration 021: RAG, Local Chunk Embeddings và Giải thích có trích dẫn (W4-Q2)
-- Người phụ trách: Tạ Trần Vinh Quang (W4-Q2)
-- Bảng: app.regulation_chunk_embeddings, app.ai_rag_explanations
-- ==============================================================================

-- 1. Bảng RegulationChunkEmbeddings (Chỉ mục vector cho trích đoạn quy chế đã duyệt)
CREATE TABLE IF NOT EXISTS app.regulation_chunk_embeddings (
    chunk_id BIGINT PRIMARY KEY REFERENCES app.regulation_chunks(chunk_id) ON DELETE CASCADE,
    embedding_model VARCHAR(100) NOT NULL,
    embedding_dim INT NOT NULL,
    embedding_vector REAL[] NOT NULL,
    chunk_hash VARCHAR(64) NOT NULL,
    indexed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reg_chunk_emb_model ON app.regulation_chunk_embeddings (embedding_model);

-- 2. Bảng AiRagExplanations (Lưu trữ câu giải thích có trích dẫn đã được kiểm chứng)
CREATE TABLE IF NOT EXISTS app.ai_rag_explanations (
    explanation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID NULL REFERENCES app.evaluation_runs(run_id) ON DELETE CASCADE,
    criterion_id BIGINT NULL REFERENCES app.award_criteria_versions(criteria_version_id) ON DELETE SET NULL,
    query_text TEXT NOT NULL,
    retrieved_chunk_ids BIGINT[] NOT NULL DEFAULT '{}',
    citations JSONB NOT NULL DEFAULT '[]',
    explanation_text TEXT NOT NULL,
    model VARCHAR(100) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    prompt_version VARCHAR(50) NOT NULL,
    retrieval_version VARCHAR(50) NOT NULL,
    is_sufficient_data BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rag_expl_run ON app.ai_rag_explanations (run_id);
CREATE INDEX IF NOT EXISTS idx_rag_expl_criterion ON app.ai_rag_explanations (criterion_id);

-- 3. Bảo mật Data API
REVOKE ALL ON app.regulation_chunk_embeddings, app.ai_rag_explanations FROM anon, authenticated;
