-- W4-P3: recommendations only; no award record or decision is created.
ALTER TABLE app.award_applications DROP CONSTRAINT ck_award_applications_status,
 ADD CONSTRAINT ck_award_applications_status CHECK(status IN
 ('DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','COUNCIL_PENDING','NEED_CORRECTION','RECOMMENDED','NOT_RECOMMENDED'));
CREATE TABLE app.application_reviews (
 review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id BIGINT NOT NULL REFERENCES app.award_applications(application_id),
 reviewer_id BIGINT NOT NULL REFERENCES app.users(user_id),
 assigned_by BIGINT NOT NULL REFERENCES app.users(user_id),
 assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(application_id,reviewer_id)
);
CREATE TABLE app.application_review_comments (
 comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id BIGINT NOT NULL REFERENCES app.award_applications(application_id),
 actor_id BIGINT NOT NULL REFERENCES app.users(user_id),
 action VARCHAR(30) NOT NULL,
 content VARCHAR(1000) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE app.application_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.application_review_comments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON app.application_reviews,app.application_review_comments FROM anon,authenticated;
ALTER TABLE app.notifications DROP CONSTRAINT notifications_entity_type_check,
 ADD CHECK(entity_type IN ('AWARD','ACHIEVEMENT','APPLICATION'));
