-- ==============================================================================
-- Migration 018: Kho văn bản, Phiên bản và Tiêu chí được duyệt (W3-Q2)
-- Người phụ trách: Tạ Trần Vinh Quang (W3-Q2)
-- Bảng: app.regulation_documents, app.regulation_document_versions,
--       app.regulation_chunks, app.award_criteria_versions
-- ==============================================================================

-- 1. Bảng RegulationDocuments (Kho văn bản gốc: Luật, Thông tư, Quy chế Nhà trường)
CREATE TABLE IF NOT EXISTS app.regulation_documents (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_code VARCHAR(100) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    issuing_authority VARCHAR(255) NULL,
    document_type VARCHAR(50) NOT NULL CHECK (document_type IN ('LAW', 'CIRCULAR', 'UNIVERSITY_REGULATION', 'DECISION', 'GUIDELINE')),
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reg_docs_code ON app.regulation_documents (document_code);
CREATE INDEX IF NOT EXISTS idx_reg_docs_type ON app.regulation_documents (document_type);

-- 2. Bảng RegulationDocumentVersions (Các phiên bản bất biến có mã băm SHA-256 và quan hệ thay thế)
CREATE TABLE IF NOT EXISTS app.regulation_document_versions (
    version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES app.regulation_documents(document_id) ON DELETE RESTRICT,
    version_number VARCHAR(100) NOT NULL,
    sha256_hash VARCHAR(64) NOT NULL,
    source_url VARCHAR(1000) NULL,
    signed_date DATE NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    supersedes_version_id BIGINT NULL REFERENCES app.regulation_document_versions(version_id) ON DELETE SET NULL,
    is_official BOOLEAN NOT NULL DEFAULT TRUE,
    is_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_by BIGINT NULL REFERENCES app.users(user_id) ON DELETE SET NULL,
    confirmed_at TIMESTAMPTZ NULL,
    confirmation_notes TEXT NULL,
    lhu_application_status VARCHAR(50) NOT NULL DEFAULT 'INTERNAL_CRITERIA_UNCONFIRMED'
        CHECK (lhu_application_status IN ('CONFIRMED_LHU_POLICY', 'INTERNAL_CRITERIA_UNCONFIRMED', 'SIMULATION_ONLY', 'REJECTED')),
    created_by BIGINT NOT NULL REFERENCES app.users(user_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_reg_doc_version UNIQUE (document_id, version_number),
    CONSTRAINT ck_reg_doc_version_effective CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE INDEX IF NOT EXISTS idx_reg_versions_doc_id ON app.regulation_document_versions (document_id);
CREATE INDEX IF NOT EXISTS idx_reg_versions_effective ON app.regulation_document_versions (effective_from, effective_to);
CREATE INDEX IF NOT EXISTS idx_reg_versions_confirmed ON app.regulation_document_versions (is_confirmed);

-- 3. Bảng RegulationChunks (Phân đoạn trích dẫn theo Điều, Khoản, Trang)
CREATE TABLE IF NOT EXISTS app.regulation_chunks (
    chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL REFERENCES app.regulation_document_versions(version_id) ON DELETE CASCADE,
    article_no VARCHAR(50) NULL,
    clause_no VARCHAR(50) NULL,
    page_no INT NULL,
    content TEXT NOT NULL,
    chunk_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reg_chunks_version ON app.regulation_chunks (version_id);
CREATE INDEX IF NOT EXISTS idx_reg_chunks_article ON app.regulation_chunks (article_no);

-- 4. Bảng AwardCriteriaVersions (Bộ tiêu chí khen thưởng theo phiên bản quy định)
CREATE TABLE IF NOT EXISTS app.award_criteria_versions (
    criteria_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL REFERENCES app.regulation_document_versions(version_id) ON DELETE RESTRICT,
    criterion_code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    target_type VARCHAR(20) NOT NULL CHECK (target_type IN ('INDIVIDUAL', 'COLLECTIVE', 'BOTH')),
    academic_year_id BIGINT NULL REFERENCES app.academic_years(academic_year_id) ON DELETE SET NULL,
    min_threshold NUMERIC(10, 2) NULL,
    unit_metric VARCHAR(50) NULL,
    legal_references TEXT NULL,
    is_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_by BIGINT NULL REFERENCES app.users(user_id) ON DELETE SET NULL,
    confirmed_at TIMESTAMPTZ NULL,
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_award_criteria_version_code UNIQUE (version_id, criterion_code)
);

CREATE INDEX IF NOT EXISTS idx_criteria_versions_version ON app.award_criteria_versions (version_id);
CREATE INDEX IF NOT EXISTS idx_criteria_versions_confirmed ON app.award_criteria_versions (is_confirmed);

-- 5. Thu hồi quyền truy cập Data API trực tiếp từ anon và authenticated
REVOKE ALL ON app.regulation_documents, app.regulation_document_versions, app.regulation_chunks, app.award_criteria_versions FROM anon, authenticated;
